<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import QRCode from 'qrcode';
import { api } from '../services/api';

type Session = { sessionId: string; mfaRequired?: boolean; expiresAt?: number };
type User = { id: string; username: string; displayName: string; email?: string; role: string; status: string; mfaEnabled: boolean; lastLoginAt?: string };
type Plugin = { id?: string; pluginCode: string; alias: string; description?: string; author: string; categories?: any[]; permissions?: any[]; status: string; createdBy?: string; latestVersion?: string; latestReleaseId?: string; updatedAt?: string };
type Release = { id: string; version: string; status: string; downloadUrl?: string; sha256?: string; sizeBytes?: number | null; minPlatformVersion?: string | null; createdAt?: string; publishedAt?: string };
type Todo = { type: 'plugin' | 'release'; id: string; pluginCode: string; alias: string; author?: string | null; version?: string | null; createdAt?: string };
const sessionId = ref(''); const loggedIn = ref(false); const mfaPending = ref(false); const page = ref('dashboard'); const loading = ref(false); const loginError = ref('');
const loginForm = reactive({ username: 'treasure', password: '', code: '' });
const dashboard = ref({ publishedPlugins: 0, releases: 0, activeUsers: 0, pending: 0, mfaRequired: false }); const users = ref<User[]>([]); const plugins = ref<Plugin[]>([]); const audits = ref<any[]>([]); const settings = ref<any>({}); const userInfo = ref<{ id: string; username: string; role: string }>({ id: '', username: 'admin', role: 'admin' });
const userQuery = ref(''); const pluginQuery = ref(''); const showUserDialog = ref(false); const showPluginDialog = ref(false); const showReleaseDialog = ref(false); const showVersionsDialog = ref(false); const showPluginEditDialog = ref(false); const showVersionEditDialog = ref(false); const versionsOf = ref<Plugin | null>(null); const versionRows = ref<Release[]>([]); const newToken = ref(''); const mfaSetup = ref<any>(null); const showMfaDialog = ref(false); const mfaCode = ref(''); const mfaBindDone = ref(false); const showChangePwdDialog = ref(false);
// 滚动条放在 el-card__body 上的页面（固定视口高度、卡片内部滚动）
const cardScrollPages = ['security', 'plugins', 'users'];
const userForm = reactive({ username: '', displayName: '', email: '', role: 'user', password: '666666' }); const pluginForm = reactive({ pluginCode: '', alias: '', description: '', author: '', version: '', downloadUrl: '', sha256: '', sizeBytes: 1, sizeUnit: 'MB', minPlatformVersion: '' }); const releaseForm = reactive({ pluginCode: '', version: '', downloadUrl: '', sha256: '', sizeBytes: 1, sizeUnit: 'MB', minPlatformVersion: '' }); const pluginEditForm = reactive({ id: '', pluginCode: '', alias: '', description: '', author: '', categories: '', permissions: '' }); const versionEditForm = reactive({ id: '', pluginCode: '', version: '', downloadUrl: '', sha256: '', sizeBytes: 1, sizeUnit: 'MB', minPlatformVersion: '' }); const pwdForm = reactive({ current: '', next: '', confirm: '' });
const filteredUsers = computed(() => users.value.filter((u) => `${u.username} ${u.displayName} ${u.email ?? ''}`.toLowerCase().includes(userQuery.value.toLowerCase()))); const filteredPlugins = computed(() => plugins.value.filter((p) => `${p.pluginCode} ${p.alias} ${p.author}`.toLowerCase().includes(pluginQuery.value.toLowerCase()))); const pageTitle = computed(() => ({ dashboard: '概览', todos: '待办中心', users: '用户管理', plugins: '插件管理', security: '安全设置', audit: '审计日志' }[page.value]));
const todoItems = ref<Todo[]>([]);
async function request<T>(path: string, options: RequestInit = {}, retried = false): Promise<T> {
  try {
    return await api<T>(path, options, sessionId.value);
  } catch (error) {
    // 敏感操作被 MFA 阻断（raio aal2）：弹验证码 -> 提升会话 -> 重放原请求（仅一次）
    if (!retried && error instanceof Error && error.message === '该操作必须完成 MFA 验证') {
      let code = '';
      try {
        const result = await ElMessageBox.prompt('当前操作需要完成 MFA 验证，请输入身份验证器中的 6 位验证码。', 'MFA 验证', { inputPattern: /^\d{6}$/, inputErrorMessage: '请输入 6 位数字验证码', confirmButtonText: '验证并继续', cancelButtonText: '取消' });
        code = String(result.value ?? '').trim();
      } catch { throw error; }
      try {
        const session = await api<Session>('/admin/mfa/verify', { method: 'POST', body: JSON.stringify({ code }) }, sessionId.value);
        sessionId.value = session.sessionId;
        persistSession(session.expiresAt);
        return await request<T>(path, options, true);
      } catch (verifyError) {
        if (verifyError instanceof Error) ElMessage.error(verifyError.message);
        throw error;
      }
    }
    throw error;
  }
}
const SESSION_KEY = 'tpm_admin_session'; const SESSION_ID_PATTERN = /^[A-Za-z0-9_-]{43}$/; function persistSession(expiresAt?: number) { localStorage.setItem(SESSION_KEY, JSON.stringify({ sessionId: sessionId.value, expiresAt: Number(expiresAt) || Date.now() })); } function clearSession() { localStorage.removeItem(SESSION_KEY); }
// 恢复前校验格式：sessionId 必须是 43 字符 base64url，防 Vapor 等垃圾值污染自动"已登录"
function restoreSession() { try { const raw = localStorage.getItem(SESSION_KEY); if (!raw) return; const saved = JSON.parse(raw) as { sessionId?: string; expiresAt?: number }; if (typeof saved.sessionId !== 'string' || !SESSION_ID_PATTERN.test(saved.sessionId)) { clearSession(); return; } if (typeof saved.expiresAt !== 'number' || saved.expiresAt <= Date.now()) { clearSession(); return; } sessionId.value = saved.sessionId; loggedIn.value = true; } catch { clearSession(); } }
async function login() { loginError.value = ''; loading.value = true; try { const data = await api<Session>('/admin/login', { method: 'POST', body: JSON.stringify({ username: loginForm.username, password: loginForm.password }) }); sessionId.value = data.sessionId; if (data.mfaRequired) { mfaPending.value = true; return; } loggedIn.value = true; persistSession(data.expiresAt); await loadDashboard(); loadUserInfo().catch(() => {}); } catch (error) { loginError.value = error instanceof Error ? error.message : '登录失败'; } finally { loading.value = false; } }
async function verifyMfa() { try { const data = await request<Session>('/admin/mfa/verify', { method: 'POST', body: JSON.stringify({ code: loginForm.code }) }); sessionId.value = data.sessionId; mfaPending.value = false; loggedIn.value = true; persistSession(data.expiresAt); await loadDashboard(); loadUserInfo().catch(() => {}); } catch (error) { ElMessage.error(error instanceof Error ? error.message : '验证码错误'); } }
// 先作废服务端会话再清本地（尽力而为，失败不阻塞登出）
function logout() { api('/admin/logout', { method: 'POST' }, sessionId.value).catch(() => {}); sessionId.value = ''; loggedIn.value = false; mfaPending.value = false; loginForm.password = ''; loginForm.code = ''; clearSession(); }
async function loadDashboard() { dashboard.value = await request('/admin/dashboard'); } async function loadUsers() { users.value = (await request<{ items: User[] }>('/admin/users')).items; } async function loadPlugins() { plugins.value = (await request<{ items: Plugin[] }>('/admin/plugins')).items; } async function loadAudits() { audits.value = (await request<{ items: any[] }>('/admin/audits')).items; } async function loadSettings() { settings.value = (await request<{ items: any }>('/admin/settings')).items; }
async function go(next: string) { page.value = next; if (next === 'dashboard') await loadDashboard(); if (next === 'todos') await loadTodos(); if (next === 'users') await loadUsers(); if (next === 'plugins') await loadPlugins(); if (next === 'audit') await loadAudits(); if (next === 'security') await loadSettings(); }
async function loadTodos() { todoItems.value = (await request<{ items: Todo[] }>('/admin/todos')).items; }
async function approveTodo(row: Todo) { await request(`/admin/plugins/${row.pluginCode}/review`, { method: 'POST', body: JSON.stringify({ action: 'approve' }) }); ElMessage.success('已通过，插件已发布'); await afterTodoAction(); }
async function rejectTodo(row: Todo) { await request(`/admin/plugins/${row.pluginCode}/review`, { method: 'POST', body: JSON.stringify({ action: 'reject' }) }); ElMessage.success('已驳回'); await afterTodoAction(); }
async function approveReleaseTodo(row: Todo) { await request(`/admin/todos/releases/${row.id}/review`, { method: 'POST', body: JSON.stringify({ action: 'approve' }) }); ElMessage.success('版本已通过发布'); await afterTodoAction(); }
async function rejectReleaseTodo(row: Todo) { await request(`/admin/todos/releases/${row.id}/review`, { method: 'POST', body: JSON.stringify({ action: 'reject' }) }); ElMessage.success('版本已驳回'); await afterTodoAction(); }
async function afterTodoAction() { await loadTodos(); await loadDashboard(); await loadPlugins(); }
function statusText(s: string) { return ({ active: '正常', disabled: '已禁用', draft: '草稿', pending_review: '待审核', published: '已发布', revoked: '已下线', deleted: '已删除' } as any)[s] ?? s; } function statusType(s: string) { return s === 'published' || s === 'active' ? 'success' : s === 'disabled' || s === 'revoked' || s === 'deleted' ? 'danger' : 'warning'; }
function openUserForm() { Object.assign(userForm, { username: '', displayName: '', email: '', role: 'user', password: '666666' }); showUserDialog.value = true; } async function createUser() { await request('/admin/users', { method: 'POST', body: JSON.stringify(userForm) }); showUserDialog.value = false; ElMessage.success('用户已创建'); await loadUsers(); }
async function toggleUser(user: User) { await request(`/admin/users/${user.id}`, { method: 'PATCH', body: JSON.stringify({ status: user.status === 'active' ? 'disabled' : 'active' }) }); await loadUsers(); }
async function confirmMfaClose() { try { const self = await request<{ items: { mfaEnabled?: boolean } }>('/admin/settings'); if (self.items?.mfaEnabled !== true) return true; } catch { return true; } try { const result = await ElMessageBox.prompt('关闭 MFA 需要验证，请输入当前账户的 6 位验证码。', 'MFA 验证', { inputPattern: /^\d{6}$/, inputErrorMessage: '请输入 6 位数字验证码', confirmButtonText: '确认', cancelButtonText: '取消' }); const session = await api<Session>('/admin/mfa/verify', { method: 'POST', body: JSON.stringify({ code: String(result.value ?? '').trim() }) }, sessionId.value); sessionId.value = session.sessionId; persistSession(session.expiresAt); return true; } catch (error) { if (error instanceof Error) ElMessage.error(error.message); return false; } }
async function toggleUserMfa(user: User) { if (user.mfaEnabled) { if (!(await confirmMfaClose())) return; const result = await request<any>(`/admin/users/${user.id}`, { method: 'PATCH', body: JSON.stringify({ mfaEnabled: false }) }); showMfaDialog.value = false; mfaSetup.value = null; mfaCode.value = ''; ElMessage.success('MFA 已关闭'); await loadUsers(); return; } try { const setup = await request<{ uri: string; secret: string }>('/admin/mfa/enroll', { method: 'POST', body: JSON.stringify({ userId: user.id }) }); mfaSetup.value = { ...setup, qr: await QRCode.toDataURL(setup.uri), userId: user.id }; mfaCode.value = ''; mfaBindDone.value = false; showMfaDialog.value = true; } catch (error) { if (error instanceof Error) ElMessage.error(error.message); } }
async function verifyMfaBind() { const code = mfaCode.value.trim(); if (!/^\d{6}$/.test(code)) return ElMessage.warning('请输入 6 位验证码'); try { await request('/admin/mfa/verify-bind', { method: 'POST', body: JSON.stringify({ userId: mfaSetup.value?.userId, code }) }); } catch (error) { if (error instanceof Error) ElMessage.error(error.message); return; } mfaBindDone.value = true; settings.value.mfaEnabled = true; ElMessage.success('MFA 绑定成功，已开启'); showMfaDialog.value = false; mfaSetup.value = null; mfaCode.value = ''; await loadUsers().catch(() => {}); await loadSettings().catch(() => {}); }
function onMfaDialogClose() { if (!mfaBindDone.value) settings.value.mfaEnabled = false; mfaSetup.value = null; mfaCode.value = ''; mfaBindDone.value = false; }
async function deleteUser(user: User) { try { await ElMessageBox.confirm(`确定删除用户「${user.displayName || user.username}」？删除后该账户无法登录，历史操作保留。`, '删除确认', { type: 'warning' }); } catch { return; } await request(`/admin/users/${user.id}`, { method: 'DELETE' }); ElMessage.success('用户已删除'); await loadUsers(); }
const showResetPwdDialog = ref(false); const resetPwdTarget = ref<User | null>(null); const resetPwdInput = ref('');
function openResetPassword(user: User) { resetPwdTarget.value = user; resetPwdInput.value = ''; showResetPwdDialog.value = true; }
async function confirmResetPassword() { if (resetPwdInput.value.length < 8) return ElMessage.warning('新密码至少 8 位'); if (!resetPwdTarget.value) return; try { await request(`/admin/users/${resetPwdTarget.value.id}/reset-password`, { method: 'POST', body: JSON.stringify({ newPassword: resetPwdInput.value }) }); ElMessage.success('密码已重置'); showResetPwdDialog.value = false; } catch (error) { if (error instanceof Error) ElMessage.error(error.message); } }
function openPluginForm() { Object.assign(pluginForm, { pluginCode: '', alias: '', description: '', author: '', version: '', downloadUrl: '', sha256: '', sizeBytes: 1, sizeUnit: 'MB', minPlatformVersion: '' }); showPluginDialog.value = true; } async function createPlugin() { await request('/admin/plugins/with-release', { method: 'POST', body: JSON.stringify({ plugin: { pluginCode: pluginForm.pluginCode, alias: pluginForm.alias, description: pluginForm.description, author: pluginForm.author }, release: { version: pluginForm.version, downloadUrl: pluginForm.downloadUrl, sha256: pluginForm.sha256, sizeBytes: Number(pluginForm.sizeBytes) * (pluginForm.sizeUnit === 'KB' ? 1024 : 1024 * 1024), minPlatformVersion: pluginForm.minPlatformVersion.trim() || null, manifest: { name: pluginForm.pluginCode, version: pluginForm.version } } }) }); showPluginDialog.value = false; ElMessage.success('插件登记成功'); await loadPlugins(); }
function openReleaseForm(plugin?: Plugin) { Object.assign(releaseForm, { pluginCode: plugin?.pluginCode ?? '', version: '', downloadUrl: '', sha256: '', sizeBytes: 1, sizeUnit: 'MB', minPlatformVersion: '' }); showReleaseDialog.value = true; } async function createRelease() { await request(`/admin/plugins/${releaseForm.pluginCode}/releases`, { method: 'POST', body: JSON.stringify({ version: releaseForm.version, downloadUrl: releaseForm.downloadUrl, sha256: releaseForm.sha256, sizeBytes: Number(releaseForm.sizeBytes) * (releaseForm.sizeUnit === 'KB' ? 1024 : 1024 * 1024), minPlatformVersion: releaseForm.minPlatformVersion.trim() || null, manifest: { name: releaseForm.pluginCode, version: releaseForm.version } }) }); showReleaseDialog.value = false; ElMessage.success('版本登记成功'); await loadPlugins(); }
function openPluginEdit(plugin: Plugin) { Object.assign(pluginEditForm, { id: plugin.id ?? '', pluginCode: plugin.pluginCode, alias: plugin.alias, description: plugin.description ?? '', author: plugin.author, categories: Array.isArray(plugin.categories) ? plugin.categories.join(',') : '', permissions: Array.isArray(plugin.permissions) ? JSON.stringify(plugin.permissions) : '' }); showPluginEditDialog.value = true; }
async function savePluginEdit() { let categories: string[] = pluginEditForm.categories.split(',').map((s) => s.trim()).filter(Boolean); let permissions: any[] = []; if (pluginEditForm.permissions.trim()) { try { const parsed = JSON.parse(pluginEditForm.permissions); if (!Array.isArray(parsed)) throw new Error('非数组'); permissions = parsed; } catch { return ElMessage.error('权限声明必须是 JSON 数组'); } } await request(`/admin/plugins/${pluginEditForm.id}`, { method: 'PATCH', body: JSON.stringify({ alias: pluginEditForm.alias, description: pluginEditForm.description, author: pluginEditForm.author, categories, permissions }) }); showPluginEditDialog.value = false; ElMessage.success('插件信息已更新'); await loadPlugins(); }
function openReleaseEdit(row: Release) { const bytes = row.sizeBytes && row.sizeBytes > 0 ? row.sizeBytes : 0; const unit = bytes >= 1024 * 1024 ? 'MB' : 'KB'; Object.assign(versionEditForm, { id: row.id, pluginCode: versionsOf.value?.pluginCode ?? '', version: row.version, downloadUrl: row.downloadUrl ?? '', sha256: row.sha256 ?? '', sizeBytes: bytes ? (unit === 'MB' ? bytes / (1024 * 1024) : bytes / 1024) : 1, sizeUnit: unit, minPlatformVersion: row.minPlatformVersion ?? '' }); showVersionEditDialog.value = true; }
async function saveReleaseEdit() { await request(`/admin/releases/${versionEditForm.id}`, { method: 'PATCH', body: JSON.stringify({ downloadUrl: versionEditForm.downloadUrl, sha256: versionEditForm.sha256, sizeBytes: Number(versionEditForm.sizeBytes) * (versionEditForm.sizeUnit === 'KB' ? 1024 : 1024 * 1024), minPlatformVersion: versionEditForm.minPlatformVersion.trim() || null }) }); showVersionEditDialog.value = false; ElMessage.success('版本信息已更新'); await loadVersions(); await loadPlugins(); }
async function openVersions(plugin: Plugin) { versionsOf.value = plugin; await loadVersions(); showVersionsDialog.value = true; }
async function loadVersions() { if (!versionsOf.value) return; versionRows.value = (await request<{ items: Release[] }>(`/admin/plugins/${versionsOf.value.pluginCode}/releases`)).items; }
async function revokeVersion(row: Release) { try { await ElMessageBox.confirm(`确定下线版本 v${row.version}？下线后市场不再提供该版本。`, '下线确认', { type: 'warning' }); } catch { return; } await request(`/admin/releases/${row.id}/revoke`, { method: 'POST' }); ElMessage.success('版本已下线'); await loadVersions(); await loadPlugins(); }
async function deleteVersion(row: Release) { try { await ElMessageBox.confirm(`确定删除版本 v${row.version}？`, '删除确认', { type: 'warning' }); } catch { return; } await request(`/admin/releases/${row.id}`, { method: 'DELETE' }); ElMessage.success('版本已删除'); await loadVersions(); await loadPlugins(); }
function formatSize(bytes?: number | null) { if (bytes == null || bytes <= 0) return '-'; if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(2)} MB`; if (bytes >= 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${bytes} B`; }
function formatTime(value?: string | number | null) { if (value === null || value === undefined || value === '') return '-'; const d = new Date(value); if (Number.isNaN(d.getTime())) return '-'; const p = (n: number) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`; }
async function disablePlugin(plugin: Plugin) { try { await ElMessageBox.confirm(`确定下线插件「${plugin.alias}」？市场将不再展示该插件。`, '下线确认', { type: 'warning' }); } catch { return; } await request(`/admin/plugins/${plugin.pluginCode}/disable`, { method: 'POST' }); ElMessage.success('插件已下线'); await loadPlugins(); }
async function deletePlugin(plugin: Plugin) { try { await ElMessageBox.confirm(`确定删除插件「${plugin.alias}」？删除后不可恢复。`, '删除确认', { type: 'warning' }); } catch { return; } await request(`/admin/plugins/${plugin.pluginCode}`, { method: 'DELETE' }); ElMessage.success('插件已删除'); await loadPlugins(); }
async function toggleMfa() { const nowEnabled = settings.value.mfaEnabled; if (nowEnabled) { try { const setup = await request<{ uri: string; secret: string }>('/admin/mfa/enroll', { method: 'POST', body: JSON.stringify({}) }); mfaSetup.value = { ...setup, qr: await QRCode.toDataURL(setup.uri), userId: settings.value?.id }; mfaCode.value = ''; mfaBindDone.value = false; showMfaDialog.value = true; } catch (error) { settings.value.mfaEnabled = false; if (error instanceof Error) ElMessage.error(error.message); } } else { if (!(await confirmMfaClose())) { settings.value.mfaEnabled = true; return; } try { await request('/admin/mfa/disable', { method: 'POST' }); showMfaDialog.value = false; mfaSetup.value = null; mfaCode.value = ''; ElMessage.success('MFA 已关闭'); } catch (error) { settings.value.mfaEnabled = true; if (error instanceof Error) ElMessage.error(error.message); } } } async function saveSecurity() { await request('/admin/settings', { method: 'PUT', body: JSON.stringify({ mfaEnabled: settings.value.mfaEnabled, tokenTtlSeconds: settings.value.tokenTtlSeconds }) }); ElMessage.success('安全设置已保存'); }
async function restorePlugin(plugin: Plugin) { await request(`/admin/plugins/${plugin.pluginCode}/review`, { method: 'POST', body: JSON.stringify({ action: 'restore' }) }); ElMessage.success('插件已恢复发布'); await loadPlugins(); }
// 角色化的插件操作判断：admin 全部可操作；operator 无任何按钮；user 仅可操作自己创建的插件
function canOperate(plugin: Plugin) { const role = userInfo.value.role; if (role === 'admin') return true; if (role === 'operator') return false; return plugin.createdBy === userInfo.value.id; }
async function changePassword() { if (pwdForm.next.length < 8) return ElMessage.warning('新密码至少 8 位'); if (pwdForm.next !== pwdForm.confirm) return ElMessage.warning('两次输入的新密码不一致'); await request('/admin/me/password', { method: 'POST', body: JSON.stringify({ currentPassword: pwdForm.current, newPassword: pwdForm.next }) }); ElMessage.success('密码已修改'); showChangePwdDialog.value = false; pwdForm.current = ''; pwdForm.next = ''; pwdForm.confirm = ''; }
async function loadUserInfo() { const data = await request<{ items: { id?: string; username?: string; role?: string } }>('/admin/settings'); userInfo.value = { id: data.items?.id ?? '', username: data.items?.username ?? 'admin', role: data.items?.role ?? 'admin' }; } function handleUserCommand(command: string | number | object) { if (command === 'logout') logout(); if (command === 'todos') go('todos'); if (command === 'reset-token') resetMyToken(); if (command === 'reset-password') { pwdForm.current = ''; pwdForm.next = ''; pwdForm.confirm = ''; showChangePwdDialog.value = true; } }
async function resetMyToken() { if (!userInfo.value.id) return ElMessage.warning('账号信息未加载'); if (!(await confirmMfaClose())) return; const result = await request<{ token: string; expiresAt: number }>(`/admin/users/${userInfo.value.id}/reset-token`, { method: 'POST' }); newToken.value = result.token; await ElMessageBox.alert(`<div class="token-result"><p>新 token（有效期至 ${formatTime(result.expiresAt)}）</p><code>${result.token}</code></div>`, 'Token 重置成功', { dangerouslyUseHTMLString: true, confirmButtonText: '复制并关闭', callback: async () => { await navigator.clipboard?.writeText(result.token); } }); }
function handleSessionExpired() { logout(); }
onMounted(() => { restoreSession(); if (loggedIn.value) { loadDashboard().catch(() => logout()); loadUserInfo().catch(() => {}); } window.addEventListener('tpm:session-expired', handleSessionExpired); });
onUnmounted(() => { window.removeEventListener('tpm:session-expired', handleSessionExpired); });
</script>

<template>
  <div v-if="!loggedIn" class="auth-shell"><el-card class="auth-card"><div class="brand"><div class="brand-mark">T</div><div><b>Treasure 插件市场</b><small>管理控制台</small></div></div><template v-if="!mfaPending"><h1>管理员登录</h1><p class="muted">登录后管理插件、版本与安全策略。</p><el-form label-width="64px" label-position="left" @submit.prevent="login"><el-form-item><template #label><span class="label-justify"><span>用</span><span>户</span><span>名</span></span></template><el-input v-model="loginForm.username" /></el-form-item><el-form-item><template #label><span class="label-justify"><span>密</span><span>码</span></span></template><el-input v-model="loginForm.password" type="password" show-password /></el-form-item><el-alert v-if="loginError" :title="loginError" type="error" show-icon :closable="false" /><el-button class="full" type="primary" native-type="submit" :loading="loading">登录</el-button></el-form></template><template v-else><h1>MFA 验证</h1><p class="muted">请输入身份验证器中的 6 位验证码。</p><el-input v-model="loginForm.code" maxlength="6" inputmode="numeric" /><div style="display:flex;gap:10px;margin-top:16px"><el-button style="flex:1" @click="mfaPending = false">返回</el-button><el-button style="flex:1" type="primary" @click="verifyMfa">继续</el-button></div></template></el-card></div>
  <el-container v-else class="layout"><el-aside width="240px" class="aside"><div class="aside-brand"><div class="brand-mark">T</div><span>插件市场<br /><small>管理控制台</small></span></div><el-menu :default-active="page" @select="go"><el-menu-item index="dashboard">概览</el-menu-item><el-menu-item v-if="userInfo.role === 'admin'" index="todos">待办中心</el-menu-item><el-menu-item v-if="userInfo.role === 'admin'" index="users">用户管理</el-menu-item><el-menu-item index="plugins">插件管理</el-menu-item><el-menu-item v-if="userInfo.role !== 'operator'" index="security">安全设置</el-menu-item><el-menu-item v-if="userInfo.role === 'admin'" index="audit">审计日志</el-menu-item></el-menu></el-aside><el-container><el-header class="header"><div><h2>{{ pageTitle }}</h2><span class="muted">Treasure 插件市场服务端</span></div><el-dropdown @command="handleUserCommand"><span class="user-chip" style="cursor:pointer;display:inline-flex;align-items:center;gap:6px"><el-badge v-if="userInfo.role === 'admin'" :value="dashboard.pending" :hidden="dashboard.pending === 0" :offset="[4, -2]"><svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor" style="display:block"><path d="M12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm0 2c-4 0-8 2-8 6v2h16v-2c0-4-4-6-8-6z" /></svg></el-badge><svg v-else viewBox="0 0 24 24" width="16" height="16" fill="currentColor" style="display:block"><path d="M12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm0 2c-4 0-8 2-8 6v2h16v-2c0-4-4-6-8-6z" /></svg>{{ userInfo.username }}</span><template #dropdown><el-dropdown-menu><el-dropdown-item disabled>角色：{{ userInfo.role === 'admin' ? '管理员' : userInfo.role === 'operator' ? '运营' : '用户' }}</el-dropdown-item><el-dropdown-item v-if="userInfo.role === 'admin'" command="todos">待办中心{{ dashboard.pending > 0 ? `（${dashboard.pending}）` : '' }}</el-dropdown-item><el-dropdown-item command="reset-token">重置 Token</el-dropdown-item><el-dropdown-item command="reset-password">重置密码</el-dropdown-item><el-dropdown-item divided command="logout">退出登录</el-dropdown-item></el-dropdown-menu></template></el-dropdown></el-header><el-main :class="['main', cardScrollPages.includes(page) ? 'main-card-scroll' : '']">
    <section v-if="page === 'dashboard'"><div class="page-head"><div><h1>市场概览</h1><p class="muted">查看发布数据、账号安全和近期操作。</p></div><el-button type="primary" @click="go('plugins')">管理插件</el-button></div><div class="stats"><el-card><span>已发布插件</span><strong>{{ dashboard.publishedPlugins }}</strong></el-card><el-card><span>公开 Release</span><strong>{{ dashboard.releases }}</strong></el-card><el-card><span>活跃用户</span><strong>{{ dashboard.activeUsers }}</strong></el-card><el-card><span>待审核</span><strong>{{ dashboard.pending }}</strong></el-card></div></section>
    <section v-else-if="page === 'todos'"><div class="page-head"><div><h1>待办中心</h1><p class="muted">统一处理插件与版本的审核请求。</p></div></div><el-card><el-table :data="todoItems" stripe><el-table-column label="类型" width="90"><template #default="{ row }"><el-tag :type="row.type === 'plugin' ? 'primary' : 'success'">{{ row.type === 'plugin' ? '插件' : '版本' }}</el-tag></template></el-table-column><el-table-column label="待审内容" min-width="260"><template #default="{ row }"><b>{{ row.alias }}</b><div class="muted">@{{ row.pluginCode }}<template v-if="row.type === 'release'"> · 提交版本 v{{ row.version }}</template></div></template></el-table-column><el-table-column label="提交时间" width="190"><template #default="{ row }">{{ formatTime(row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="180"><template #default="{ row }"><el-button v-if="row.type === 'plugin'" link type="success" @click="approveTodo(row)">通过</el-button><el-button v-if="row.type === 'plugin'" link type="danger" @click="rejectTodo(row)">驳回</el-button><el-button v-if="row.type === 'release'" link type="success" @click="approveReleaseTodo(row)">通过</el-button><el-button v-if="row.type === 'release'" link type="danger" @click="rejectReleaseTodo(row)">驳回</el-button></template></el-table-column></el-table><el-empty v-if="!todoItems.length" description="暂无待办" /></el-card></section>
    <section v-else-if="page === 'users'"><div class="page-head"><div><h1>用户管理</h1><p class="muted">用户、角色、状态及 MFA 安全控制。</p></div><el-button type="primary" @click="openUserForm">新增用户</el-button></div><el-card><div class="toolbar"><el-input v-model="userQuery" placeholder="搜索用户名、姓名或邮箱" clearable /></div><el-table :data="filteredUsers" stripe><el-table-column label="用户" min-width="200"><template #default="{ row }"><b>{{ row.displayName }}</b><div class="muted">@{{ row.username }} · {{ row.email }}</div></template></el-table-column><el-table-column prop="role" label="角色" width="110" /><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column label="MFA" width="100"><template #default="{ row }"><el-tag :type="row.mfaEnabled ? 'success' : 'info'">{{ row.mfaEnabled ? '已启用' : '未启用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="400" fixed="right"><template #default="{ row }"><el-button v-if="row.status === 'active'" link @click="toggleUser(row)">停用</el-button><el-button v-else link @click="toggleUser(row)">启用</el-button><el-button link @click="toggleUserMfa(row)">{{ row.mfaEnabled ? '关闭 MFA' : '开启 MFA' }}</el-button><el-button v-if="row.status === 'active' && row.id !== userInfo.id" link type="warning" @click="openResetPassword(row)">重置密码</el-button><el-button v-if="row.status === 'disabled'" link type="danger" @click="deleteUser(row)">删除</el-button></template></el-table-column></el-table></el-card></section>
    <section v-else-if="page === 'plugins'"><div class="page-head"><div><h1>插件管理</h1><p class="muted">插件登记、版本历史、发布与软删除。</p></div><el-button v-if="userInfo.role !== 'operator'" type="primary" @click="openPluginForm">登记插件</el-button></div><el-card><div class="toolbar"><el-input v-model="pluginQuery" placeholder="搜索插件编码、名称或作者" clearable /></div><el-table :data="filteredPlugins" stripe><el-table-column label="插件" min-width="220"><template #default="{ row }"><b>{{ row.alias }}</b><div class="muted">{{ row.pluginCode }}</div></template></el-table-column><el-table-column prop="latestVersion" label="最新版本" width="120" /><el-table-column prop="author" label="作者" width="140" /><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column v-if="userInfo.role !== 'operator'" label="操作" min-width="380" fixed="right"><template #default="{ row }"><el-button v-if="canOperate(row)" link @click="openPluginEdit(row)">编辑</el-button><el-button v-if="canOperate(row)" link @click="openReleaseForm(row)">新增版本</el-button><el-button v-if="canOperate(row)" link @click="openVersions(row)">版本</el-button><template v-if="canOperate(row) && row.status === 'published'"><el-button link type="warning" @click="disablePlugin(row)">下线</el-button></template><template v-else-if="canOperate(row) && row.status === 'disabled'"><el-button link type="success" @click="restorePlugin(row)">恢复</el-button><el-button link type="danger" @click="deletePlugin(row)">删除</el-button></template></template></el-table-column></el-table></el-card></section>
    <section v-else-if="page === 'security'"><div class="page-head"><div><h1>安全设置</h1><p class="muted">MFA 与本账户安全管理。</p></div><el-button v-if="userInfo.role === 'admin'" type="primary" @click="saveSecurity">保存设置</el-button></div><el-card class="security-card"><h3>MFA 验证器</h3><el-switch v-model="settings.mfaEnabled" active-text="开启 MFA" inactive-text="关闭 MFA" @change="toggleMfa" /><el-alert class="mt" type="info" :closable="false" title="开启后登录需要 TOTP 验证码。" /><template v-if="userInfo.role === 'admin'"><h3 class="mt">全局 Token 有效期</h3><el-form class="mt"><el-form-item label="Token 有效期（秒）"><el-input-number v-model="settings.tokenTtlSeconds" :min="60" :max="86400" /></el-form-item></el-form></template></el-card></section>
    <section v-else><div class="page-head"><div><h1>审计日志</h1><p class="muted">登录、MFA、token 和插件生命周期操作。</p></div></div><el-card><el-table :data="audits" stripe><el-table-column label="时间" width="190"><template #default="{ row }">{{ formatTime(row.createdAt) }}</template></el-table-column><el-table-column prop="action" label="操作" /><el-table-column prop="target" label="资源" /><el-table-column prop="actorId" label="操作者" /></el-table></el-card></section>
  </el-main></el-container></el-container>
  <el-dialog v-model="showUserDialog" title="新增用户" width="520px"><el-form label-position="top"><el-form-item label="用户名"><el-input v-model="userForm.username" /></el-form-item><el-form-item label="显示名"><el-input v-model="userForm.displayName" /></el-form-item><el-form-item label="邮箱"><el-input v-model="userForm.email" /></el-form-item><el-form-item label="角色"><el-select v-model="userForm.role"><el-option label="用户" value="user" /><el-option label="管理员" value="admin" /><el-option label="运营" value="operator" /></el-select></el-form-item><el-form-item label="初始密码"><el-input v-model="userForm.password" type="password" show-password /></el-form-item></el-form><template #footer><el-button @click="showUserDialog = false">取消</el-button><el-button type="primary" @click="createUser">创建</el-button></template></el-dialog>
  <el-dialog v-model="showPluginDialog" title="登记插件" width="620px" top="8vh"><div class="dialog-body-scroll"><el-form label-position="top"><el-form-item label="插件编码"><el-input v-model="pluginForm.pluginCode" /></el-form-item><el-form-item label="名称"><el-input v-model="pluginForm.alias" /></el-form-item><el-form-item label="描述"><el-input v-model="pluginForm.description" type="textarea" /></el-form-item><el-form-item label="作者"><el-input v-model="pluginForm.author" /></el-form-item><el-form-item label="版本"><el-input v-model="pluginForm.version" placeholder="1.0.0" /></el-form-item><el-form-item label="最低平台版本"><el-input v-model="pluginForm.minPlatformVersion" placeholder="2.0.0，可留空" /></el-form-item><el-form-item label="下载地址"><el-input v-model="pluginForm.downloadUrl" /></el-form-item><el-form-item label="SHA-256"><el-input v-model="pluginForm.sha256" /></el-form-item><el-form-item label="大小"><div style="display:flex;gap:8px"><el-input-number v-model="pluginForm.sizeBytes" :min="1" /><el-select v-model="pluginForm.sizeUnit" style="width:96px" placeholder="单位"><el-option label="KB" value="KB" /><el-option label="MB" value="MB" /></el-select></div></el-form-item></el-form></div><template #footer><el-button @click="showPluginDialog = false">取消</el-button><el-button type="primary" @click="createPlugin">登记</el-button></template></el-dialog>
  <el-dialog v-model="showReleaseDialog" title="新增版本" width="560px" top="12vh"><el-form label-position="top"><el-form-item label="插件编码"><el-input v-model="releaseForm.pluginCode" /></el-form-item><el-form-item label="版本"><el-input v-model="releaseForm.version" /></el-form-item><el-form-item label="最低平台版本"><el-input v-model="releaseForm.minPlatformVersion" placeholder="2.0.0，可留空" /></el-form-item><el-form-item label="下载地址"><el-input v-model="releaseForm.downloadUrl" /></el-form-item><el-form-item label="SHA-256"><el-input v-model="releaseForm.sha256" /></el-form-item><el-form-item label="大小"><div style="display:flex;gap:8px"><el-input-number v-model="releaseForm.sizeBytes" :min="1" /><el-select v-model="releaseForm.sizeUnit" style="width:96px" placeholder="单位"><el-option label="KB" value="KB" /><el-option label="MB" value="MB" /></el-select></div></el-form-item></el-form><template #footer><el-button @click="showReleaseDialog = false">取消</el-button><el-button type="primary" @click="createRelease">登记</el-button></template></el-dialog>
  <el-dialog v-model="showPluginEditDialog" title="编辑插件信息" width="620px" top="8vh"><div class="dialog-body-scroll"><el-form label-position="top"><el-form-item label="插件编码"><el-input v-model="pluginEditForm.pluginCode" disabled /></el-form-item><el-form-item label="名称"><el-input v-model="pluginEditForm.alias" /></el-form-item><el-form-item label="描述"><el-input v-model="pluginEditForm.description" type="textarea" /></el-form-item><el-form-item label="作者"><el-input v-model="pluginEditForm.author" /></el-form-item><el-form-item label="分类"><el-input v-model="pluginEditForm.categories" placeholder="多个分类用英文逗号分隔，如 开发工具,效率工具" /></el-form-item><el-form-item label="权限声明"><el-input v-model="pluginEditForm.permissions" type="textarea" :rows="3" placeholder='JSON 数组，如 [{"name":"filesystem:read"}]，可留空' /></el-form-item></el-form></div><template #footer><el-button @click="showPluginEditDialog = false">取消</el-button><el-button type="primary" @click="savePluginEdit">保存</el-button></template></el-dialog>
  <el-dialog v-model="showVersionEditDialog" title="编辑版本信息" width="560px" top="12vh"><el-form label-position="top"><el-form-item label="插件编码"><el-input v-model="versionEditForm.pluginCode" disabled /></el-form-item><el-form-item label="版本"><el-input v-model="versionEditForm.version" disabled /></el-form-item><el-form-item label="下载地址"><el-input v-model="versionEditForm.downloadUrl" /></el-form-item><el-form-item label="SHA-256"><el-input v-model="versionEditForm.sha256" /></el-form-item><el-form-item label="大小"><div style="display:flex;gap:8px"><el-input-number v-model="versionEditForm.sizeBytes" :min="1" /><el-select v-model="versionEditForm.sizeUnit" style="width:96px" placeholder="单位"><el-option label="KB" value="KB" /><el-option label="MB" value="MB" /></el-select></div></el-form-item><el-form-item label="最低平台版本"><el-input v-model="versionEditForm.minPlatformVersion" placeholder="2.0.0，可留空" /></el-form-item></el-form><template #footer><el-button @click="showVersionEditDialog = false">取消</el-button><el-button type="primary" @click="saveReleaseEdit">保存</el-button></template></el-dialog>
  <el-dialog v-model="showVersionsDialog" :title="`版本管理 · ${versionsOf?.pluginCode ?? ''}`" width="780px" top="10vh"><el-table :data="versionRows" stripe><el-table-column prop="version" label="版本号" width="110" /><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column label="大小" width="120"><template #default="{ row }">{{ formatSize(row.sizeBytes) }}</template></el-table-column><el-table-column label="创建时间" width="190"><template #default="{ row }">{{ formatTime(row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="220"><template #default="{ row }"><el-button link @click="openReleaseEdit(row)">编辑</el-button><el-button v-if="row.status !== 'revoked' && row.status !== 'deleted'" link type="warning" @click="revokeVersion(row)">下线</el-button><el-button v-if="row.status === 'revoked'" link type="danger" @click="deleteVersion(row)">删除</el-button></template></el-table-column></el-table><el-empty v-if="!versionRows.length" description="暂无版本" /></el-dialog>
  <el-dialog v-model="showResetPwdDialog" :title="`重置密码 · ${resetPwdTarget?.displayName || (resetPwdTarget?.username ?? '')}`" width="420px"><el-form label-position="top"><el-form-item label="新密码（至少 8 位）"><el-input v-model="resetPwdInput" type="password" show-password placeholder="请输入新密码" @keyup.enter="confirmResetPassword" /></el-form-item></el-form><template #footer><el-button @click="showResetPwdDialog = false">取消</el-button><el-button type="primary" @click="confirmResetPassword">确认重置</el-button></template></el-dialog>
  <el-dialog v-model="showMfaDialog" title="绑定 MFA 验证器" width="440px" @close="onMfaDialogClose"><p class="muted">请使用 Google Authenticator 等应用扫描二维码或手动输入密钥，再输入应用生成的 6 位验证码完成绑定。</p><div style="text-align:center;margin:12px 0"><img v-if="mfaSetup?.qr" :src="mfaSetup.qr" alt="MFA 二维码" style="width:180px;height:180px;display:inline-block" /></div><el-input :model-value="mfaSetup?.uri || mfaSetup?.secret" readonly /><el-button class="mt" style="width:100%" @click="navigator.clipboard?.writeText(mfaSetup?.uri || mfaSetup?.secret)">复制绑定信息</el-button><el-input v-model="mfaCode" maxlength="6" inputmode="numeric" placeholder="输入身份验证器中的 6 位验证码" style="margin-top:12px" /><template #footer><el-button @click="showMfaDialog = false">取消</el-button><el-button type="primary" @click="verifyMfaBind">确认</el-button></template></el-dialog>
  <el-dialog v-model="showChangePwdDialog" title="重置密码" width="420px" @closed="pwdForm.current = ''; pwdForm.next = ''; pwdForm.confirm = ''"><el-form label-position="top" @submit.prevent="changePassword"><el-form-item label="当前密码"><el-input v-model="pwdForm.current" type="password" show-password /></el-form-item><el-form-item label="新密码"><el-input v-model="pwdForm.next" type="password" show-password placeholder="至少 8 位" /></el-form-item><el-form-item label="确认新密码"><el-input v-model="pwdForm.confirm" type="password" show-password /></el-form-item></el-form><template #footer><el-button @click="showChangePwdDialog = false">取消</el-button><el-button type="primary" native-type="submit" @click="changePassword">确认</el-button></template></el-dialog>
</template>
