import type { FileEntry } from './fileScanner';

export const mockFileTree: FileEntry[] = [
  { name: '工作.md', path: '工作.md', isDirectory: false },
  { name: '周报.md', path: '周报.md', isDirectory: false },
  { name: '第1周.md', path: '第1周.md', isDirectory: false },
  { name: '第2周.md', path: '第2周.md', isDirectory: false },
  { name: '第3周.md', path: '第3周.md', isDirectory: false },
  { name: '会议纪要.md', path: '会议纪要.md', isDirectory: false },
  { name: '项目计划.md', path: '项目计划.md', isDirectory: false },
  { name: '待办清单.md', path: '待办清单.md', isDirectory: false },
  { name: '生活.md', path: '生活.md', isDirectory: false },
  { name: '购物清单.md', path: '购物清单.md', isDirectory: false },
  { name: '旅行计划.md', path: '旅行计划.md', isDirectory: false },
  { name: '健身记录.md', path: '健身记录.md', isDirectory: false },
  { name: '随笔.md', path: '随笔.md', isDirectory: false },
  { name: '日记.md', path: '日记.md', isDirectory: false },
  { name: '2024-01.md', path: '2024-01.md', isDirectory: false },
  { name: '2024-02.md', path: '2024-02.md', isDirectory: false },
  { name: '晨间随想.md', path: '晨间随想.md', isDirectory: false },
  { name: '灵感速记.md', path: '灵感速记.md', isDirectory: false },
  { name: '夜间感悟.md', path: '夜间感悟.md', isDirectory: false },
  { name: '学习.md', path: '学习.md', isDirectory: false },
  { name: '读书笔记.md', path: '读书笔记.md', isDirectory: false },
  { name: '深度工作.md', path: '深度工作.md', isDirectory: false },
  { name: '原则.md', path: '原则.md', isDirectory: false },
  { name: '编程练习.md', path: '编程练习.md', isDirectory: false },
  { name: '课程笔记.md', path: '课程笔记.md', isDirectory: false },
  { name: '英语单词.md', path: '英语单词.md', isDirectory: false },
  { name: '资源收藏.md', path: '资源收藏.md', isDirectory: false },
  { name: 'README.md', path: 'README.md', isDirectory: false },
  { name: 'index.md', path: 'index.md', isDirectory: false },
  { name: '模板.md', path: '模板.md', isDirectory: false },
];
